---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgCPJqnAav9jxQHpqaUqX1WohSsYHw2ImnBQJXGvI3ReGfnDjJX4E5V8locPqMe0C/t5VmLYDNDgMcEmCG7qixoc8/N7CSwte+HfAk11R7DlywbMkDIV2LOFbaYt/3+GdoQQJojYEL53KieZmsth6bTfJvTZeZOUb8U/dfhNP8THpQaZVxAUtmcXpLQW3+m0mM5uQtj3kuWK/QkqRbRiTdMSeQV0L3otGf5+EpVFD6eiBdQrxAlPLoMmtJ8oQO73GbTJk1Zw3FnSpTtvD7cHSnsnVMrbrZzI1aIWfH7hTjwm/ccE1BX9W8Je/HyZirZ0mDNiwl+lwejP/S1wj9LvZZNsCdqEJntzU8WsERu07W5PhGSlTh84xnmUL5SqOWfcL4HP+qyL4sMf2EU3NTdXbuyynMjflmIbg0ds1NlPv0khZICXP78TPhUtjILwQdiycQeW9nV2k4Hdg7WT/FVOy1Ozm1hlu5gYUQ+UnPmSLlCOiWlKxxuIG/PJF8Lrw7K5VOMFs+hWo8/NPsYt+mcV43D6n7hhJ/PuTEB92n1kTLLPk2CmeVd948cKTOde+89Z0imnGsLPmOOyMKKq5LDcSY+Yoh+GrRRMC8IGMVwfeCbIrn9Ki9dMqBcan87yuKBsn7F4hhz8fjd9Vl3oaqfYTLtVWumRP1rQEfgMB23x8o5qz2y6HGw4OIHUX6FG3f7Puygw6l5bjIURz0f9WzA+qlTxvyGy32NsXf9KK8sCMtL/H2mFCx4M+A==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
